LIBRARY IEEE;
 USE IEEE.STD_LOGIC_1164.ALL;
 ENTITY audio IS -- ´Î¶¥²ãÉè¼Æ
 PORT ( CLK12MHZ : IN STD_LOGIC;
 INDEX1 : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
 SPKOUT : OUT STD_LOGIC );
 END;
 ARCHITECTURE one OF audio IS
 COMPONENT ToneTaba
 PORT ( Index : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
 Tone : OUT INTEGER RANGE 0 TO 16#7FF# );
 END COMPONENT;
 COMPONENT Speakera
 PORT ( clk : IN STD_LOGIC;
 Tone : IN INTEGER RANGE 0 TO 16#7FF#;
 SpkS : OUT STD_LOGIC );
 END COMPONENT;
 SIGNAL Tone2 : INTEGER RANGE 0 TO 16#7FF#;
 BEGIN
 u1 : ToneTaba PORT MAP (Index=>Index1, Tone=>Tone2);
 u2 : Speakera PORT MAP (clk=>CLK12MHZ,Tone=>Tone2,
 SpkS=>SPKOUT );
 END;